export const ACTION_ADD_SHIP = 'ADD_SHIP';
export const ACTION_ATTACK_SHIP = 'ATTACK_SHIP';
export const ACTION_ATTACK_COMPUTER_SHIP = 'ATTACK_COMPUTER_SHIP';
export const ACTION_READY = 'READY';
export const ACTION_ADD_COMPUTER_SHIP = 'ADD_COMPUTER_SHIP'
export const ACTION_WINNER = 'WINNER'
export const ACTION_SELECT_OPTIONS = 'SELECT_OPTIONS';
export const ACTION_RESTART = 'RESTART'